---
title: Purdue ARC Wiki
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  wiki:
    title: Wiki
    output: true
    permalink: "/:name"
defaults:
- scope:
    path: ''
  values:
    layout: article
    pageview: false
    sidebar:
      nav: wiki
    license: false
    aside:
      toc: true
    show_edit_on_github: true
    show_date: true
    lightbox: true
text_skin: ocean
highlight_theme: default
url: 
baseurl: 
description: 'Learn about the robotics projects that we build at Purdue ARC!

'
lang: 
author:
  type: organization
  name: Purdue ARC
  url: www.purduearc.com
  avatar: 
  bio: The Autonomous Robotics Club of Purdue was created to grow the skills and abilities
    of its members through design projects centered around advanced autonomous robotics
    systems. It provides hands-on, real world experience to interdisciplinary teams
    using industry standard tools and practices.
  email: autonomy@purdue.edu
  twitter: PurdueRobotClub
  github: purdue-arc
repository: purdue-arc/wiki
repository_tree: master
paths:
  root: 
  home: 
  wiki: 
  rss: 
excerpt_separator: "<!--more-->"
license: CC-BY-NC-4.0
toc:
  selectors: 
mathjax: true
mathjax_autoNumber: 
mermaid: true
chart: true
paginate: 8
paginate_path: "/page:num"
sources: 
sharing:
  provider: false
  addthis:
    id: 
comments:
  provider: gitalk
  gitalk:
    clientID: bd0f29091842158ea699
    clientSecret: 6406f50dbe27c3da0c7eaa27f0f3d93c4ce70f5d
    repository: wiki
    owner: purdue-arc
    admin:
    - raghavauppuluri13
    - hmccarty
    - jrbaxter0
pageview:
  provider: false
  leancloud:
    app_id: 
    app_key: 
    app_class: 
search:
  provider: default
  google:
    custom_search_engine_id: 
analytics:
  provider: google
  google:
    tracking_id: UA-199808191-1
    anonymize_ip: false
markdown: kramdown
highlighter: rouge
permalink: date
exclude:
- CHANGELOG.md
- HOW_TO_RELEASE.md
- Gemfile
- Gemfile.lock
- LICENSE
- README-*.md
- README.md
- gulpfile.js
- jekyll-text-theme.gemspec
- package-lock.json
- package.json
- "/node_modules"
- "/vendor"
collections_dir: wiki
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jemoji
